SELECT CAST(DATE_FORMAT(START_DATE, "%c") AS UNSIGNED) AS MONTH, CAR_ID, COUNT(*) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= "2022-08-01" AND
    START_DATE < "2022-11-00"
  AND CAR_ID IN (
    SELECT CAR_ID AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= "2022-08-01" AND
    START_DATE < "2022-11-00"
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
GROUP BY CAR_ID, MONTH
ORDER BY 1 ASC, 2 DESC