-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, PRODUCT.PRICE * SUM(OFFLINE_SALE.SALES_AMOUNT) AS TOTAL_AMOUNT
FROM OFFLINE_SALE
         INNER JOIN PRODUCT
                    ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
ORDER BY 2 DESC, 1 ASC