WITH ANI AS
(SELECT INS.ANIMAL_ID, INS.NAME, DATEDIFF(OUTS.DATETIME, INS.DATETIME) AS DU from ANIMAL_INS AS INS
JOIN ANIMAL_OUTS AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY DU DESC
LIMIT 2)

SELECT ANIMAL_ID, NAME FROM ANI;