-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, sum(S.SALES * B.PRICE) AS TOTAL_SALES FROM BOOK_SALES AS S
join BOOK AS B
     on S.BOOK_ID = B.BOOK_ID
join AUTHOR AS A
     on B.AUTHOR_ID = A.AUTHOR_ID
WHERE substring(S.SALES_DATE, 1, 7) = '2022-01'
group by B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC