-- on 으로 조인하기전에 where 절을 걸고 싶을때 On에서 먼저하면 된다. DATE_FORMAT 공부 필요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK
INNER JOIN AUTHOR
ON AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID AND
    BOOK.CATEGORY = '경제'
ORDER BY BOOK.PUBLISHED_DATE ASC