SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD FROM APPOINTMENT AS A
JOIN DOCTOR AS D
     on A.MDDR_ID = D.DR_ID
JOIN PATIENT  AS P
     on A.PT_NO = P.PT_NO
where A.MCDP_CD = 'CS' AND substring(A.APNT_YMD, 1, 10) = '2022-04-13' AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD ASC;